### ISSUE TITLE
Tibetan market

### ISSUE THREAD

**Issue by aartitripathi** [junkjam/cms.blog.junkjam.in#20]
![janpath-market](https://cloud.githubusercontent.com/assets/20486720/16975881/54da0848-4e68-11e6-9ab0-648cdabc32f9.JPG)
![tibetan-market-cp-2](https://cloud.githubusercontent.com/assets/20486720/16975893/66511d96-4e68-11e6-9395-8b759dcd9030.gif)
![tibetan-market-cp-4](https://cloud.githubusercontent.com/assets/20486720/16975894/665646b8-4e68-11e6-8947-80a6b2941d97.gif)

**Comment by fasihahmad** [comment]
You have added images of Janpath market.
And most importantly we have already featured uploaded images.

**Comment by fasihahmad** [comment]
Merged with PR #21
